.<<_사용자>>
. <<사용자 로그인>>
.. <<사용자 로그인 성공>>
.. <<사용자 로그인 실패 - 인가 코드가 잘못 되었을 경우>>
. <<사용자 로그아웃>>
.. <<사용자 로그아웃 성공>>
.. <<사용자 로그아웃 실패 - 인증에 실패한 경우>>
. <<사용자 refresh token 재발급>>
.. <<사용자 refresh token 재발급 성공>>
.. <<사용자 refresh token 재발급 실패 - 토큰값 없이 요청한 경우>>
.. <<사용자 refresh token 재발급 실패 - 리프레시 토큰이 만료되었을 경우>>

.<<업체 신청>>
. <<업체 신청 생성>>
.. <<업체 신청 생성 성공>>
.. <<업체 신청 생성 실패 - 입력 요청 값이 잘못된 경우>>
.. <<업체 신청 생성 실패 - 개업일이 현재 시각보다 늦은 경우>>
.. <<업체 신청 생성 실패 - 회원 인증 실패>>
.. <<업체 신청 생성 실패 - 이미 업체인 경우>>
. <<업체 신청 상세 조회>>
.. <<업체 신청 상세 조회 성공>>
.. <<업체 신청 상세 조회 실패 - 존재하지 않는 id 인 경우>>
. <<업체 신청 목록 조회>>
.. <<업체 신청 목록 조회 성공>>
. <<업체 신청 상태 변경>>
.. <<업체 신청 상태 변경 성공 - 승인>>
.. <<업체 신청 상태 변경 성공 - 거절>>
.. <<업체 신청 상태 변경 성공 - 거절된 것을 승인 대기로 변경>>
.. <<업체 신청 상태 변경 실패 - 회원 인증 실패>>
.. <<업체 신청 상태 변경 실패 - 관리자가 아닌 회원의 요청>>
.. <<업체 신청 상태 변경 실패 - 존재하지 않는 업체 신청인 경우>>
.. <<업체 신청 상태 변경 실패 - 현재와 같은 상태로의 변경 요청인 경우>>
.. <<업체 신청 상태 변경 실패 - 이미 업체인 회원의 승인 요청인 경우>>

.<<_주문>>
. <<주문 생성>>
.. <<주문 생성 성공>>
.. <<주문 생성 실패(Forbidden)>>
.. <<주문 생성 실패(Unauthorized)>>
. <<주문 조회>>
.. <<내 주문 목록 조회 성공>>
.. <<내 주문 목록 조회 실패(Forbidden)>>
.. <<내 주문 목록 조회 실패(UnAuthorize)>>
.. <<주문 목록 조회 성공>>
.. <<주문 상세 조회 성공>>
.. <<주문 상세 조회 실패 - 존재하지 않는 주문인 경우>>
. <<주문 삭제>>
.. <<주문 삭제 성공>>
.. <<주문 삭제 실패 - 잘못된 입력값>>
.. <<주문 삭제 실패 - 인증되지 않은 사용자>>
.. <<주문 삭제 실패 - 인가되지 않은 사용자>>
.. <<주문 삭제 실패 - 잘못된 입력값>>

.<<_오퍼>>
.  <<오퍼 생성>>
.. <<오퍼 생성 성공>>
.. <<오퍼 생성 실패 - 주문이 존재하지 않는 경우>>
.. <<오퍼 생성 실패 - 글 작성 회원이 업주가 아닌 경우>>
.. <<오퍼 생성 실패 - 이미 완료된 주문인 경우>>
.. <<오퍼 생성 실패 - 이미 해당 글에 오퍼 글을 작성한 적이 있는 경우>>
.. <<오퍼 생성 실패 - 픽업 날짜가 지난 주문인 경우>>
. <<오퍼 조회>>
.. <<오퍼 조회 성공>>
.. <<오퍼 조회 실패>>
.. <<오퍼 삭제>>
.. <<오퍼 삭제 성공>>
.. <<오퍼 삭제 실패 - 존재하지 않은 주문일 경우>>
.. <<오퍼 삭제 실패 - 인증되지 않은 사용자일 경우>>
.. <<오퍼 삭제 실패 - 인가되지 않은 사용자일 경우>>
.. <<오퍼 삭제 실패 - 주문완료인 주문인 경우>>

.<<결제 내역>>
. <<결제 내역 생성>>
.. <<결제 내역 생성 성공>>
.. <<결제 내역 생성 실패 - 잘못된 입력값>>
.. <<결제 내역 생성 실패 - 인증되지 않은 사용자>>
.. <<결제 내역 생성 실패 - 인가되지 않은 사용자>>
.. <<결제 내역 생성 실패 - 존재하지 않는 주문>>

== 사용자

=== 사용자 로그인

==== 사용자 로그인 성공

operation::member/oauth 로그인 성공[snippets='http-request,request-fields,http-response,response-fields']

==== 사용자 로그인 실패 - 인가 코드가 잘못 되었을 경우

operation::member/oauth 로그인 실패 - 인가 코드가 잘못 되었을 경우[snippets='http-request,request-fields,http-response,response-fields']

=== 사용자 로그아웃

==== 사용자 로그아웃 성공

operation::member/oauth 로그아웃 성공[snippets='http-request,request-headers,http-response']

==== 사용자 로그아웃 실패 - 인증에 실패한 경우

operation::member/oauth 로그아웃 실패 - 인증에 실패한 경우[snippets='http-request,http-response,response-fields']

=== 사용자 refresh token 재발급

==== 사용자 refresh token 재발급 성공

operation::member/refresh token 재발급 성공[snippets='http-request,request-fields,http-response,response-fields']

==== 사용자 refresh token 재발급 실패 - 토큰값 없이 요청한 경우

operation::member/refresh token 재발급 실패 - 토큰값 없이 요청한 경우[snippets='http-request,http-response,response-fields']

==== 사용자 refresh token 재발급 실패 - 리프레시 토큰이 만료되었을 경우

operation::member/refresh token 재발급 실패 - 리프레시 토큰이 만료되었을 경우[snippets='http-request,request-fields,http-response,response-fields']

=== 팔로우 생성

==== 팔로우 생성 성공

operation::follow/팔로우 생성 성공[snippets='http-request,http-response']

==== 팔로우 생성 실패 - 존재하지 않는 marketId 인 경우

operation::follow/팔로우 생성 실패(BadRequest)[snippets='http-request,http-response,response-fields']

==== 팔로우 생성 실패 - 회원 인증 실패

operation::follow/팔로우 생성 실패(Unauthorized)[snippets='http-request,http-response,response-fields']

==== 팔로우 생성 실패 - 회원 권한이 아닌 경우

operation::follow/팔로우 생성 실패(Forbidden)[snippets='http-request,http-response,response-fields']

==== 팔로우 생성 실패(Conflict)

operation::follow/팔로우 생성 실패(Conflict)[snippets='http-request,http-response,response-fields']

=== 팔로우 삭제

==== 팔로우 삭제 성공

operation::follow/팔로우 삭제 성공[snippets='http-request,http-response']

==== 팔로우 삭제 실패 - 존재하지 않는 marketId 인 경우, 팔로우하지 않은 경우

operation::follow/팔로우 삭제 실패(BadRequest)[snippets='http-request,http-response,response-fields']

==== 팔로우 삭제 실패 - 회원 인증 실패

operation::follow/팔로우 삭제 실패(Unauthorized)[snippets='http-request,http-response,response-fields']

==== 팔로우 삭제 실패 - 회원 권한이 아닌 경우

operation::follow/팔로우 삭제 실패(Forbidden)[snippets='http-request,http-response,response-fields']

== 업체 신청

=== 업체 신청 생성

==== 업체 신청 생성 성공

operation::marketEnrollment/업체 신청 생성 성공[snippets='http-request,request-parts,request-parameters,http-response,response-headers']

==== 업체 신청 생성 실패 - 입력 요청 값이 잘못된 경우

operation::marketEnrollment/업체 신청 생성 실패 - 입력 요청 값이 잘못된 경우[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-fields']

==== 업체 신청 생성 실패 - 개업일이 현재 시각보다 늦은 경우

operation::marketEnrollment/업체 신청 생성 실패 - 개업일이 현재 시각보다 늦은 경우[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-fields']

==== 업체 신청 생성 실패 - 회원 인증 실패

operation::marketEnrollment/업체 신청 생성 실패 - 회원 인증 실패[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-fields']

==== 업체 신청 생성 실패 - 이미 업체인 경우

operation::marketEnrollment/업체 신청 생성 실패 - 이미 업체인 경우[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-fields']

=== 업체 신청 상세 조회

==== 업체 신청 상세 조회 성공

operation::marketEnrollment/업체 신청 상세 조회 성공[snippets='http-request,request-headers,http-response,response-fields']

==== 업체 신청 상세 조회 실패 - 존재하지 않는 id 인 경우

operation::marketEnrollment/업체 신청 상세 조회 실패 - 존재하지 않는 id 인 경우[snippets='http-request,request-headers,http-response,response-fields']

=== 업체 신청 목록 조회

==== 업체 신청 목록 조회 성공

operation::marketEnrollment/업체 신청 목록 조회 성공[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 업체 신청 상태 변경

==== 업체 신청 상태 변경 성공 - 승인

operation::marketEnrollment/업체 신청 상태 변경 성공 - 승인[snippets='http-request,request-headers,request-body,request-fields,http-response']

==== 업체 신청 상태 변경 성공 - 거절

operation::marketEnrollment/업체 신청 상태 변경 성공 - 거절[snippets='http-request,request-headers,request-body,request-fields,http-response']

==== 업체 신청 상태 변경 성공 - 거절된 것을 승인 대기로 변경

operation::marketEnrollment/업체 신청 상태 변경 성공 - 거절된 것을 승인 대기로 변경[snippets='http-request,request-headers,request-body,request-fields,http-response']

==== 업체 신청 상태 변경 실패 - 회원 인증 실패

operation::marketEnrollment/업체 신청 상태 변경 실패 - 회원 인증 실패[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']

==== 업체 신청 상태 변경 실패 - 관리자가 아닌 회원의 요청

operation::marketEnrollment/업체 신청 상태 변경 실패 - 관리자가 아닌 회원의 요청[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']

==== 업체 신청 상태 변경 실패 - 존재하지 않는 업체 신청인 경우

operation::marketEnrollment/업체 신청 상태 변경 실패 - 존재하지 않는 업체 신청인 경우[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']

==== 업체 신청 상태 변경 실패 - 현재와 같은 상태로의 변경 요청인 경우

operation::marketEnrollment/업체 신청 상태 변경 실패 - 현재와 같은 상태로의 변경 요청인 경우[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']

==== 업체 신청 상태 변경 실패 - 이미 업체인 회원의 승인 요청인 경우

operation::marketEnrollment/업체 신청 상태 변경 실패 - 이미 업체인 회원의 승인 요청인 경우[snippets='http-request,request-headers,request-body,request-fields,http-response,response-fields']

== 주문

=== 주문 생성

==== 주문 생성 성공

operation::order/주문 생성 성공[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-headers']

==== 주문 생성 실패(Forbidden)

operation::order/주문 생성 실패(Forbidden)[snippets='http-request,request-parts,request-parameters,http-response,response-fields']

==== 주문 생성 실패(Unauthorized)

operation::order/주문 생성 실패(Forbidden)[snippets='http-request,request-parts,request-parameters,http-response,response-fields']

=== 주문 조회

==== 내 주문 목록 조회 성공

operation::order/내 주문 목록 조회 성공[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

==== 내 주문 목록 조회 실패(Forbidden)

operation::order/내 주문 목록 조회 실패(Forbidden)[snippets='http-request,request-parameters,http-response,response-fields']

==== 내 주문 목록 조회 실패(UnAuthorize)

operation::order/내 주문 목록 조회 실패(Forbidden)[snippets='http-request,request-parameters,http-response,response-fields']

==== 주문 목록 조회 성공

operation::order/주문 목록 조회 성공[snippets='http-request,request-parameters,http-response,response-fields']

=== 주문 상세 조회

==== 주문 상세 조회 성공

operation::order/주문 상세 조회 성공[snippets='http-request,http-response,response-fields']

==== 주문 상세 조회 실패 - 존재하지 않는 주문인 경우

operation::order/주문 상세 조회 실패 - 존재하지 않는 주문인 경우[snippets='http-request,http-response,response-fields']

=== 주문 삭제

==== 주문 삭제 성공

operation::order/주문 삭제 성공[snippets='http-request,path-parameters,request-headers,http-response']

==== 주문 삭제 실패 - 잘못된 입력값

operation::order/주문 삭제 실패(BadRequest)[snippets='http-response']

==== 주문 삭제 실패 - 인증되지 않은 사용자

operation::order/주문 삭제 실패(Unauthorized)[snippets='http-response']

==== 주문 삭제 실패 - 인가되지 않은 사용자

operation::order/주문 삭제 실패(Forbidden)[snippets='http-response']

==== 주문 삭제 실패 - 잘못된 입력값

operation::order/주문 삭제 실패(Conflict)[snippets='http-response']

== 오퍼

=== 오퍼 생성

==== 오퍼 생성 성공

operation::offer/오퍼 생성 성공[snippets='http-request,request-headers,request-parameters,request-parts,http-response,response-headers']

==== 오퍼 생성 실패 - 주문이 존재하지 않는 경우

operation::offer/오퍼 생성 실패 - 주문이 존재하지 않는 경우[snippets='http-response']

==== 오퍼 생성 실패 - 글 작성 회원이 업주가 아닌 경우

operation::offer/오퍼 생성 실패 - 글 작성 회원이 업주가 아닌 경우[snippets='http-response']

==== 오퍼 생성 실패 - 이미 완료된 주문인 경우

operation::offer/오퍼 생성 실패 - 이미 완료된 주문인 경우[snippets='http-response']

==== 오퍼 생성 실패 - 이미 해당 글에 오퍼 글을 작성한 적이 있는 경우

operation::offer/오퍼 생성 실패 - 이미 해당 글에 오퍼 글을 작성한 적 있는 경우[snippets='http-response']

==== 오퍼 생성 실패 - 픽업 날짜가 지난 주문인 경우

operation::offer/오퍼 생성 실패 - 픽업 날짜가 지난 주문인 경우[snippets='http-response']

=== 오퍼 조회

==== 오퍼 조회 성공

operation::offer/오퍼 조회 성공[snippets='http-request,path-parameters,http-response,response-fields']

==== 오퍼 조회 실패

operation::offer/오퍼 조회 실패 - 존재하지 않는 오퍼인 경우[snippets='http-request,path-parameters,http-response,response-fields']

=== 오퍼 삭제

==== 오퍼 삭제 성공

operation::offer/오퍼 삭제 성공[snippets='http-request,path-parameters,request-headers,http-response']

==== 오퍼 삭제 실패 - 존재하지 않은 주문일 경우

operation::offer/오퍼 삭제 실패(BadRequest)[snippets='http-response']

==== 오퍼 삭제 실패 - 인증되지 않은 사용자일 경우

operation::offer/오퍼 삭제 실패(Unauthorized)[snippets='http-response']

==== 오퍼 삭제 실패 - 인가되지 않은 사용자일 경우

operation::offer/오퍼 삭제 실패(Forbidden)[snippets='http-response']

==== 오퍼 삭제 실패 - 주문완료인 주문인 경우

operation::offer/오퍼 삭제 실패(Conflict)[snippets='http-response']

== 결제 내역

=== 결제 내역 생성

==== 결제 내역 생성 성공

operation::history/결제 내역 생성 성공[snippets='http-request,request-headers,request-body,request-fields,http-response,response-headers']

==== 결제 내역 생성 실패 - 잘못된 입력값

operation::history/결제 내역 생성 실패(BadRequest)[snippets='http-response']

==== 결제 내역 생성 실패 - 인증되지 않은 사용자

operation::history/결제 내역 생성 실패(Unauthorized)[snippets='http-response']

==== 결제 내역 생성 실패 - 인가되지 않은 사용자

operation::history/결제 내역 생성 실패(Forbidden)[snippets='http-response']

==== 결제 내역 생성 실패 - 존재하지 않는 주문

operation::history/결제 내역 생성 실패(NotFound)[snippets='http-response']